#! /bin/sh

VAR="new"
COM=$1
FILE=$2
if [ "$COM" = "$VAR" ] && [ -n "$FILE" ] && [ ! -f "./article/$FILE.md" ]
then
    touch "./article/$FILE.md"
    echo "---\n
title: \n
date: $(date "+%Y-%m-%d %H:%M:%S")\n
tags:\n
categories:\n
---" > "./article/$FILE.md"
    echo "创建成功"
else
  if [ ! -n "$FILE" ]
  then
    echo "没输入文件名"
  else
    echo "命令错误"
  fi
fi
